update
Viyyy/Esil.Noise.Model-S pull request #10
Opened 2024-06-18 14:35 UTC by Fenrirlkj12

2024-06-18 14:41 UTC, Viyyy requested changes

2024-06-18 14:41 UTC, Viyyy commented on datasets/models/category.py
> +        font_path = 'utils/fonts/SimHei.ttf'  # 替换为 SimHei 字体的实际路径
font_path is not matched

2024-06-18 14:44 UTC, Viyyy requested changes

2024-06-18 14:44 UTC, Viyyy commented on datasets/SupportedSources.py
> +BIRDCLEF = BirdclefDataSource(**datasources_info['Birdclef'])
config.yml.example 里没有加上对应的配置信息

2024-06-18 14:44 UTC, Viyyy commented on datasets/models/sources.py
> +        print(os.path.join(f'train_audio', ret["filename"]))# 根据索引获取特定的记录
print 只是测试时用到，实际用的时候不需要

2024-06-18 14:57 UTC, Viyyy requested changes

2024-06-18 14:57 UTC, Viyyy commented on datasets/models/category.py
> +        fm.fontManager.addfont(font_path)
字体设置一般都写在引用后面

2024-06-18 14:57 UTC, Viyyy commented on datasets/models/category.py
> +        plt.rcParams['axes.unicode_minus'] = False
这部分重复了。

2024-06-19 07:02 UTC, Fenrirlkj12 reviewed
已完成修订

2024-06-19 07:03 UTC, Fenrirlkj12 commented
已完成修订

2024-06-19 13:53 UTC, merged